/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Article Topics
 * Id: 4ce421e9-c403-eee8-fdc2-74f09392a749
 * Codename: manufacturer
 */
export type ArticleTopics = 'aerobie' | 'chemex' | 'espro' | 'hario';
