/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const assetFolders = {
    /**
     * Caf  locations
     */
    caféLocations: {
        id: '958001d8-2228-4373-b966-5262b5b96f71',
        name: 'Café locations',
        externalId: undefined,
        folders: {}
    },

    /**
     * client logos
     */
    clientLogos: {
        id: 'e6521491-f11f-4652-b09b-5e7c600989ef',
        name: 'client logos',
        externalId: undefined,
        folders: {}
    }
} as const;
