/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const contentTypes = {
    /**
     * Article
     */
    article: {
        codename: 'article',
        id: '115171cb-49a7-4fbc-84aa-f3a614cbdf55',
        externalId: undefined,
        name: 'Article',
        elements: {
            /**
             * ArticleContent (rich_text)
             */
            articlecontent: {
                codename: 'articlecontent',
                id: '1dd2a0ac-87bc-45ef-9c01-0f6f7c30a65d',
                externalId: undefined,
                name: 'ArticleContent',
                required: true,
                type: 'rich_text'
            },

            /**
             * ArticleHeaderImage (asset)
             */
            articleheaderimage: {
                codename: 'articleheaderimage',
                id: 'abe8e6ea-9663-4189-8bad-d25c4e5577d7',
                externalId: undefined,
                name: 'ArticleHeaderImage',
                required: false,
                type: 'asset'
            },

            /**
             * Article Topics (taxonomy)
             */
            articletaxonomy: {
                codename: 'articletaxonomy',
                id: '967f226e-2705-4d35-ab6e-0b0e15d43d7a',
                externalId: undefined,
                name: 'ArticleTaxonomy',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Meta description (text)
             *
             * Length: 70–150 characters
             */
            metadata__meta_description: {
                codename: 'metadata__meta_description',
                id: '2e555cc1-1eae-520c-189e-28548904f529',
                externalId: undefined,
                name: 'Meta description',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            },

            /**
             * Meta title (text)
             *
             * Length: 30–60 characters
             */
            metadata__meta_title: {
                codename: 'metadata__meta_title',
                id: '09398b24-61ed-512e-5b5c-affd54a098e5',
                externalId: undefined,
                name: 'Meta title',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            },

            /**
             * og description (text)
             *
             * Max. 150 characters
             */
            metadata__og_description: {
                codename: 'metadata__og_description',
                id: '05987dc9-ebe3-7b61-b949-522eb42dbc0d',
                externalId: undefined,
                name: 'og:description',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            },

            /**
             * og image (asset)
             *
             * Use images that are at least 1200 × 630 px for best display on high resolution devices. At the minimum, you should use images that are 600 × 315 px to display link page posts with larger images. Images may be up to 1 MB in size.
             */
            metadata__og_image: {
                codename: 'metadata__og_image',
                id: 'ce6cda71-9d38-1d57-3ac3-ec9b2e286edd',
                externalId: undefined,
                name: 'og:image',
                required: false,
                type: 'asset',

                snippetCodename: 'metadata'
            },

            /**
             * og title (text)
             *
             * Max. 60 characters
             */
            metadata__og_title: {
                codename: 'metadata__og_title',
                id: '1db86c7a-e836-3c4e-01e6-4f704ad38ba5',
                externalId: undefined,
                name: 'og:title',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            },

            /**
             * Summary (rich_text)
             */
            summary: {
                codename: 'summary',
                id: 'dbf8b1b5-2c50-4a77-b237-b41cce430822',
                externalId: undefined,
                name: 'Summary',
                required: false,
                type: 'rich_text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '2e351eee-9826-4190-aa23-68294053a1d2',
                externalId: undefined,
                name: 'Title',
                required: true,
                type: 'text'
            },

            /**
             * twitter creator (text)
             */
            metadata__twitter_creator: {
                codename: 'metadata__twitter_creator',
                id: '68f65095-c9b4-05d6-a473-2883c2f0c7af',
                externalId: undefined,
                name: 'twitter:creator',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            },

            /**
             * twitter description (text)
             *
             * A description that concisely summarizes the content as appropriate for presentation within a Tweet. You should not re-use the title as the description, or use this field to describe the general services provided by the website. Max. 150 characters.
             */
            metadata__twitter_description: {
                codename: 'metadata__twitter_description',
                id: 'b7d1dd8b-a5d8-2ad8-2f57-49881363f6f7',
                externalId: undefined,
                name: 'twitter:description',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            },

            /**
             * twitter image (asset)
             *
             * Twitter's recommendation: A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card should be at least 280 × 150 px. Images may be up to 1 MB in size.Let's go for 560 × 300 px.
             */
            metadata__twitter_image: {
                codename: 'metadata__twitter_image',
                id: '63793ba4-6004-a93c-68ca-52a1f0482bca',
                externalId: undefined,
                name: 'twitter:image',
                required: false,
                type: 'asset',

                snippetCodename: 'metadata'
            },

            /**
             * twitter site (text)
             */
            metadata__twitter_site: {
                codename: 'metadata__twitter_site',
                id: '34213fdf-0015-8f4f-e5e6-83c6842cff4a',
                externalId: undefined,
                name: 'twitter:site',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            },

            /**
             * twitter title (text)
             *
             * Max. 60 characters
             */
            metadata__twitter_title: {
                codename: 'metadata__twitter_title',
                id: 'b208d3dc-bd8d-b1af-5ef0-747650730ba7',
                externalId: undefined,
                name: 'twitter:title',
                required: false,
                type: 'text',

                snippetCodename: 'metadata'
            }
        }
    },

    /**
     * Client
     */
    client: {
        codename: 'client',
        id: '77d55eb5-1e79-4380-bbdd-f156d0b33116',
        externalId: undefined,
        name: 'Client',
        elements: {
            /**
             * Logo (asset)
             */
            logo: {
                codename: 'logo',
                id: '2cd454d0-7013-43fd-808e-e666dff588a7',
                externalId: undefined,
                name: 'Logo',
                required: false,
                type: 'asset'
            },

            /**
             * Name (text)
             */
            name: {
                codename: 'name',
                id: 'a9dcc11d-892b-49f9-9141-91c10715be5b',
                externalId: undefined,
                name: 'Name',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Experiment
     */
    experiment: {
        codename: 'experiment',
        id: '29bdfce6-9542-4207-9262-343f48cd1e9a',
        externalId: undefined,
        name: 'Experiment',
        elements: {
            /**
             * ExperimentBody (rich_text)
             */
            experimentbody: {
                codename: 'experimentbody',
                id: 'b8447d7d-6577-4bb7-863c-96771067d606',
                externalId: undefined,
                name: 'ExperimentBody',
                required: false,
                type: 'rich_text'
            },

            /**
             * ExperimentTitle (text)
             */
            experimenttitle: {
                codename: 'experimenttitle',
                id: 'fbd73d84-6aa1-4006-9f62-48b12c7117c4',
                externalId: undefined,
                name: 'ExperimentTitle',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Hero
     */
    hero: {
        codename: 'hero',
        id: 'eb5ff1b4-d972-4801-873e-2d30d9b82330',
        externalId: undefined,
        name: 'Hero',
        elements: {
            /**
             * HeroImage (asset)
             */
            heroimage: {
                codename: 'heroimage',
                id: '93876f62-901b-4802-8c49-021dd03be224',
                externalId: undefined,
                name: 'HeroImage',
                required: false,
                type: 'asset'
            },

            /**
             * HeroText (text)
             */
            herotext: {
                codename: 'herotext',
                id: '238b1016-0734-4561-9060-632651605ea1',
                externalId: undefined,
                name: 'HeroText',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Page
     */
    page: {
        codename: 'page',
        id: '02060b17-d31b-4ac8-a821-dc0790f7f19c',
        externalId: undefined,
        name: 'Page',
        elements: {
            /**
             * Body (rich_text)
             */
            body: {
                codename: 'body',
                id: 'a9ac071f-a117-40a0-992b-c5466d189a82',
                externalId: undefined,
                name: 'Body',
                required: true,
                type: 'rich_text'
            },

            /**
             * Client List (modular_content)
             */
            client_list: {
                codename: 'client_list',
                id: 'd8a50e4e-9e63-4ea3-9b7c-44ff29e823ba',
                externalId: undefined,
                name: 'Client List',
                required: false,
                type: 'modular_content'
            },

            /**
             * Slug (url_slug)
             */
            slug: {
                codename: 'slug',
                id: 'f1e3fd8b-5573-42ee-b34c-7f1188b041fd',
                externalId: undefined,
                name: 'Slug',
                required: false,
                type: 'url_slug'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'b13922c4-8649-4dc8-a23d-b69e11fe22ac',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Page
     */
    page_39aa00f: {
        codename: 'page_39aa00f',
        id: '39aa00f1-bbaf-43af-84d8-7b79478082fa',
        externalId: undefined,
        name: 'Page',
        elements: {
            /**
             * Content (modular_content)
             */
            content: {
                codename: 'content',
                id: 'b40981be-e475-4144-8cc1-6f9b86600307',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'modular_content'
            },

            /**
             * Show in navigation (multiple_choice)
             */
            show_in_navigation: {
                codename: 'show_in_navigation',
                id: '87193234-fb86-4221-a246-b4c0a6b6a5d2',
                externalId: undefined,
                name: 'Show in navigation',
                required: false,
                type: 'multiple_choice',
                options: {
                    yes: {
                        name: 'Yes',
                        id: 'c629b1a0-0ef1-433c-b9c4-2a9b6c494122',
                        codename: 'yes',
                        externalId: undefined
                    },
                    no: {
                        name: 'No',
                        id: '8032a213-0692-46dd-9038-ebc7b521c386',
                        codename: 'no',
                        externalId: undefined
                    }
                }
            },

            /**
             * Subpages (subpages)
             */
            subpages: {
                codename: 'subpages',
                id: '28055c18-1c42-477b-a7c2-032d39f18026',
                externalId: undefined,
                name: 'Subpages',
                required: false,
                type: 'subpages'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'be8b9875-3555-4656-85a2-9c5d0c6e30ce',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * URL (url_slug)
             */
            url: {
                codename: 'url',
                id: '68efc282-07a4-4591-8b73-0e8ced4d896c',
                externalId: undefined,
                name: 'URL',
                required: false,
                type: 'url_slug'
            }
        }
    },

    /**
     * Web spotlight root
     */
    web_spotlight_root: {
        codename: 'web_spotlight_root',
        id: '40b7df0c-eb1a-4007-913b-1ee1007b057a',
        externalId: undefined,
        name: 'Web spotlight root',
        elements: {
            /**
             * Content (modular_content)
             */
            content: {
                codename: 'content',
                id: '960113a5-6b9f-4c24-84ca-8f9f9d8d01b5',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'modular_content'
            },

            /**
             * Subpages (subpages)
             */
            subpages: {
                codename: 'subpages',
                id: 'b6568c87-27b8-42ee-9786-40d7c9bcc438',
                externalId: undefined,
                name: 'Subpages',
                required: false,
                type: 'subpages'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'b0da7732-1e56-4398-b882-15db2bd907b0',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    }
} as const;
