/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const workflows = {
    /**
     * Default
     * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
     * Published step Id: b4363ccd-8f21-45fd-a840-5843d7b7f008
     */
    default: {
        codename: 'default',
        id: '00000000-0000-0000-0000-000000000000',
        name: 'Default',
        steps: {
            archived: {
                name: 'Archived',
                codename: 'archived',
                id: '7a535a69-ad34-47f8-806a-def1fdf4d391'
            },
            published: {
                name: 'Published',
                codename: 'published',
                id: 'b4363ccd-8f21-45fd-a840-5843d7b7f008'
            },
            scheduled: {
                name: 'Scheduled',
                codename: 'scheduled',
                id: '9d2b0228-4d0d-4c23-8b49-01a698857709'
            },
            draft: {
                name: 'Draft',
                codename: 'draft',
                id: '88ac5e6e-1c5c-4638-96e1-0d61221ad5bf'
            },
            approved: {
                name: 'Approved',
                codename: 'approved',
                id: 'a1b9efa3-8270-47e4-8d8d-b182710d1e3b'
            }
        }
    }
} as const;
