import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Client
 * Id: 77d55eb5-1e79-4380-bbdd-f156d0b33116
 * Codename: client
 */
export type Client = IContentItem<{
    /**
     * Logo (asset)
     * Required: false
     * Id: 2cd454d0-7013-43fd-808e-e666dff588a7
     * Codename: logo
     */
    logo: Elements.AssetsElement;

    /**
     * Name (text)
     * Required: false
     * Id: a9dcc11d-892b-49f9-9141-91c10715be5b
     * Codename: name
     */
    name: Elements.TextElement;
}>;
