import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Hero
 * Id: eb5ff1b4-d972-4801-873e-2d30d9b82330
 * Codename: hero
 */
export type Hero = IContentItem<{
    /**
     * HeroImage (asset)
     * Required: false
     * Id: 93876f62-901b-4802-8c49-021dd03be224
     * Codename: heroimage
     */
    heroimage: Elements.AssetsElement;

    /**
     * HeroText (text)
     * Required: false
     * Id: 238b1016-0734-4561-9060-632651605ea1
     * Codename: herotext
     */
    herotext: Elements.TextElement;
}>;
