import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Page
 * Id: 39aa00f1-bbaf-43af-84d8-7b79478082fa
 * Codename: page_39aa00f
 */
export type Page = IContentItem<{
    /**
     * Content (modular_content)
     * Required: false
     * Id: b40981be-e475-4144-8cc1-6f9b86600307
     * Codename: content
     */
    content: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Show in navigation (multiple_choice)
     * Required: false
     * Id: 87193234-fb86-4221-a246-b4c0a6b6a5d2
     * Codename: show_in_navigation
     */
    show_in_navigation: Elements.MultipleChoiceElement;

    /**
     * Subpages (subpages)
     * Required: false
     * Id: 28055c18-1c42-477b-a7c2-032d39f18026
     * Codename: subpages
     */
    subpages: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Title (text)
     * Required: false
     * Id: be8b9875-3555-4656-85a2-9c5d0c6e30ce
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * URL (url_slug)
     * Required: false
     * Id: 68efc282-07a4-4591-8b73-0e8ced4d896c
     * Codename: url
     */
    url: Elements.UrlSlugElement;
}>;
