import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Page } from './page_39aa00f';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Web spotlight root
 * Id: 40b7df0c-eb1a-4007-913b-1ee1007b057a
 * Codename: web_spotlight_root
 */
export type WebSpotlightRoot = IContentItem<{
    /**
     * Content (modular_content)
     * Required: false
     * Id: 960113a5-6b9f-4c24-84ca-8f9f9d8d01b5
     * Codename: content
     */
    content: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Subpages (subpages)
     * Required: false
     * Id: b6568c87-27b8-42ee-9786-40d7c9bcc438
     * Codename: subpages
     */
    subpages: Elements.LinkedItemsElement<Page>;

    /**
     * Title (text)
     * Required: false
     * Id: b0da7732-1e56-4398-b882-15db2bd907b0
     * Codename: title
     */
    title: Elements.TextElement;
}>;
